load("@io_bazel_rules_scala//scala:scala.bzl", "scala_macro_library")

scala_macro_library(
    name = "meta",
    srcs = glob(["**/*.scala"]),    
    deps = [],    
    visibility = [
        "//visibility:public"
    ],
)
