#!/bin/bash

if [ -z "$IS_IN_NIX" ]; then
    echo ""
    echo "You're running Bazel from outside of nix-shell!"
    echo "This will incur a slight overhead on each bazel invocation"
    echo "Consider entering a nix-shell if you'd like to avoid this overhead"
    echo ""

    eval nix-shell --command \"bazel $@\"
else
    $BAZEL_REAL "$@"
fi
